name: ChatHeads
version: '${version}'
main: dev.jsinco.chatheads.ChatHeads
authors:
  - Jsinco
  - Minso
api-version: '1.21'
depend:
  - ProtocolLib
softdepend:
  - floodgate
  - PlaceholderAPI
commands:
  chatheads:
    description: 'Base command'
    permission: 'chatheads.command'
    aliases:
      - chathead
permissions:
  chatheads.toggle:
    description: 'Disable chat heads'
    default: true
  chatheads.orientation:
    description: 'Change chat head orientation'
    default: true
  chatheads.reload:
    description: 'Reload chat heads'
    default: op